{
  "formatVersion": "1.1",
  "component": {
    "group": "com.javassist",
    "module": "modify",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "azb2eafc4ne4vajbsrjxzqnple"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "modify-1.0.0.jar",
          "url": "modify-1.0.0.jar",
          "size": 15374,
          "sha512": "de33e57ddac7c3325a08bdf6eb5595de06c54466f50b536b13e58009ec3dc1191a925a44cd79868141676c391788624c7b0b6be2a87c6a51e27f296b595c8d5c",
          "sha256": "85f46a91ad01cacf3a1cd2db9586feb102bfe5b6ebee465d7591bd09c27c3305",
          "sha1": "81d11f0175184409ccddf05829faddc7bf0994af",
          "md5": "4fbd122c00669851722b7dcb1ed88f67"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.20.0-GA"
          }
        }
      ],
      "files": [
        {
          "name": "modify-1.0.0.jar",
          "url": "modify-1.0.0.jar",
          "size": 15374,
          "sha512": "de33e57ddac7c3325a08bdf6eb5595de06c54466f50b536b13e58009ec3dc1191a925a44cd79868141676c391788624c7b0b6be2a87c6a51e27f296b595c8d5c",
          "sha256": "85f46a91ad01cacf3a1cd2db9586feb102bfe5b6ebee465d7591bd09c27c3305",
          "sha1": "81d11f0175184409ccddf05829faddc7bf0994af",
          "md5": "4fbd122c00669851722b7dcb1ed88f67"
        }
      ]
    }
  ]
}
